### ISSUE TITLE
Marginal power calculation with sample size higher than 1000 in survival 

### ISSUE THREAD

**Issue by ipval6** [gpaux/Mediana#2]
Congratulations for your nice package

I am trying to estimate marginal power in a clinical scenario with different sample sizes. The problem is when I reach large sample size (> 1000), the result gets NaN. 
I have no idea why it is happening but seems rare...
I attach the example. 
I would really appreciate if you can help me with this. Probably, I am not considering some factor.

Thanks in advance, Irene

### Requirements
require(Mediana)

### Adjusting rate to experimental data

analysis.model = AnalysisModel() +
  Test(id = "Placebo vs treatment",
       samples = samples("Placebo", "Treatment"),
       method = "LogrankTest") +
  Statistic(id = "Events Placebo",
            samples = samples("Placebo"),
            method = "EventCountStat") +
  Statistic(id = "Events Treatment",
            samples = samples("Treatment"),
            method = "EventCountStat")  +
  Statistic(id = "Patients Placebo",
            samples = samples("Placebo"),
            method = "PatientCountStat") +
  Statistic(id = "Patients Treatment",
            samples = samples("Treatment"),
            method = "PatientCountStat") 

evaluation.model = EvaluationModel() +
  Criterion(id = "Marginal power",
            method = "MarginalPower",
            tests = tests("Placebo vs treatment"),
            labels = c("Placebo vs treatment"),
            par = parameters(alpha = 0.025))  +
  Criterion(id = "Mean Events",
            method = "MeanSumm",
            statistics = statistics("Events Placebo", "Events Treatment"),
            labels = c("Mean Events Placebo", "Mean Events Treatment")) +
  Criterion(id = "Mean Patients",
            method = "MeanSumm",
            statistics = statistics("Patients Placebo", "Patients Treatment"),
            labels = c("Mean Patients Placebo", "Mean Patients Treatment"))

sim.parameters = SimParameters(n.sims = 1000, proc.load = "full", seed = 42938001)

data.model = DataModel() +
  OutcomeDist(outcome.dist = "ExpoDist", outcome.type = "event") +
  Sample(id = "Placebo",
         outcome.par = parameters(parameters(rate =0.05))) +
  Sample(id = "Treatment",
         outcome.par = parameters(parameters(rate =0.05*0.6))) +
  SampleSize(1500) +
  Design(enroll.period = 1,
         study.duration = 5,
         enroll.dist = "UniformDist",
         dropout.dist = "ExpoDist",
         dropout.dist.par = parameters(rate = 0.0115))

results = CSE(data.model, analysis.model, evaluation.model, sim.parameters)

**Comment by gpaux** [comment]
Thanks for your feedback! The issue comes from the computation of the one sided log rank test pvalue. I have created another temporary function you can use (see below LogrankTest_v2) and specified it in the analysis model.

```{r }
require(Mediana)

# Revised function returning the one-sided pvalue for a Log-rank test
LogrankTest_v2 = function(sample.list, parameter){
  require(survival)
  # Determine the function call, either to generate the p-value or to return description
  call = (parameter[[1]] == "Description")
  
  if (call == FALSE | is.na(call)) {
    
    # No parameters are defined
    if (is.na(parameter[[2]])) {
      larger = TRUE
    }
    else {
      if (!all(names(parameter[[2]]) %in% c("larger"))) stop("Analysis model: LogRankTest test: this function accepts only one argument (larger)")
      # Parameters are defined but not the larger argument
      if (!is.logical(parameter[[2]]$larger)) stop("Analysis model: LogRankTest test: the larger argument must be logical (TRUE or FALSE).")
      larger = parameter[[2]]$larger
    }
    
    # Sample list is assumed to include two data frames that represent two analysis samples
    
    # Outcomes in Sample 1
    outcome1 = sample.list[[1]][, "outcome"]
    # Remove the missing values due to dropouts/incomplete observations
    outcome1.complete = outcome1[stats::complete.cases(outcome1)]
    # Observed events in Sample 1 (negation of censoring indicators)
    event1 = !sample.list[[1]][, "patient.censor.indicator"]
    event1.complete = event1[stats::complete.cases(outcome1)]
    # Sample size in Sample 1
    n1 = length(outcome1.complete)
    
    # Outcomes in Sample 2
    outcome2 = sample.list[[2]][, "outcome"]
    # Remove the missing values due to dropouts/incomplete observations
    outcome2.complete = outcome2[stats::complete.cases(outcome2)]
    # Observed events in Sample 2 (negation of censoring indicators)
    event2 = !sample.list[[2]][, "patient.censor.indicator"]
    event2.complete = event2[stats::complete.cases(outcome2)]
    # Sample size in Sample 2
    n2 = length(outcome2.complete)
    
    # Create combined samples of outcomes, censoring indicators (all events are observed) and treatment indicators
    outcome = c(outcome1.complete, outcome2.complete)
    event = c(event1.complete, event2.complete)
    treatment = c(rep(0, n1), rep(1, n2))
    
    data = data.frame(time = outcome,
                      event = event,
                      treatment = treatment)
    data = data[order(data$time),]
    
    # Get log-rank test statistic
    LR = survdiff(Surv(time, event) ~ treatment, data = data)
    HR = (LR$obs[2]/LR$exp[2])/(LR$obs[1]/LR$exp[1])
    
    # Compute one-sided p-value
    pval = pchisq(LR$chisq, length(LR$n)-1, lower.tail = FALSE)/2
    result = ifelse((HR<1 & isTRUE(larger)) | (HR>1 & isFALSE(larger)), pval, 1)
    
  }
  
  else if (call == TRUE) {
    result = list("Log-rank test")
  }
  
  return(result)
  
}

analysis.model = AnalysisModel() +
  Test(id = "Placebo vs treatment",
       samples = samples("Placebo", "Treatment"),
       method = "LogrankTest_v2",) +
  Statistic(id = "Events Placebo",
            samples = samples("Placebo"),
            method = "EventCountStat") +
  Statistic(id = "Events Treatment",
            samples = samples("Treatment"),
            method = "EventCountStat") +
  Statistic(id = "Patients Placebo",
            samples = samples("Placebo"),
            method = "PatientCountStat") +
  Statistic(id = "Patients Treatment",
            samples = samples("Treatment"),
            method = "PatientCountStat")

evaluation.model = EvaluationModel() +
  Criterion(id = "Marginal power",
            method = "MarginalPower",
            tests = tests("Placebo vs treatment"),
            labels = c("Placebo vs treatment"),
            par = parameters(alpha = 0.025)) +
  Criterion(id = "Mean Events",
            method = "MeanSumm",
            statistics = statistics("Events Placebo", "Events Treatment"),
            labels = c("Mean Events Placebo", "Mean Events Treatment")) +
  Criterion(id = "Mean Patients",
            method = "MeanSumm",
            statistics = statistics("Patients Placebo", "Patients Treatment"),
            labels = c("Mean Patients Placebo", "Mean Patients Treatment"))

sim.parameters = SimParameters(n.sims = 1000, proc.load = "full", seed = 42938001)

data.model = DataModel() +
  OutcomeDist(outcome.dist = "ExpoDist", outcome.type = "event") +
  Sample(id = "Placebo",
         outcome.par = parameters(parameters(rate = 0.05))) +
  Sample(id = "Treatment",
         outcome.par = parameters(parameters(rate = 0.05*0.6))) +
  SampleSize(1500) +
  Design(enroll.period = 1,
         study.duration = 3,
         enroll.dist = "UniformDist",
         dropout.dist = "ExpoDist",
         dropout.dist.par = parameters(rate = 0.0115))

results = CSE(data.model, analysis.model, evaluation.model, sim.parameters)
summary(results)
```

**Comment by ipval6** [comment]
It seems to work perfectly now.
Thank you again for your help!
