### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by gmalbaiceta** [gpaux/Mediana#5]
Thanks for this interesting package. I've been exploring some survival models and I've noticed that there is an integer overflow error when samples sizes are slightly larger than 2000 cases, so no calculations of Marginal Power, Hazard ratio or p-values are given, showing a NA/NaN instead.
Reviewing the code, the problem is in "LogrankTest.R",  line 40. Multiplication of large numbers in that line causes the error, as the result is higher than the maximum allowed value in R. 
It can be solved by adding an "as.numeric" before the first term of the multiplication, so the result is converted to numeric:
` data$v1 = ifelse(data$n.risk.prior > 1, 
                     (as.numeric(data$n.risk1.prior) * data$n.risk2.prior * data$eventtot * (data$n.risk.prior - data$eventtot))/(data$n.risk.prior^2 * (data$n.risk.prior - 1)),
                     0)`
Could this be corrected in the main branch? Thank you very much for your contribution.

**Comment by gpaux** [comment]
Which Medians version are you using? Have you checked with the latest GitHub version? A workaround has been implemented before
https://github.com/gpaux/Mediana/issues/2

**Comment by gpaux** [comment]
The workaround has not been published yet on CRAN, will published it soon in v1.0.9. Thanks for your feedback!
