### ISSUE TITLE
[Question] Could you, please, cross-validate the calculation gMCP vs. Mediana in this scenario?

### ISSUE THREAD

**Issue by Generalized** [gpaux/Mediana#6]
For this 2-family parallel gatekeeper with Hochberg truncated at: 0.5 in the 1st family and 1 (classic) in the 2nd family:

![obraz](https://user-images.githubusercontent.com/60151643/219379976-7a74b9d2-78cb-4e6c-b2a0-7f5d8acb64e3.png)

I get a discrepancy between gMCP and Mediana.

Mediana:
```{r}
rawp   <- c(0.01, 0.013, 0.01, 0.01)
family <- families(family1 = c(1, 2), family2 = c(3, 4))
gamma  <- families(family1 = 0.5, family2 = 1)

AdjustPvalues(rawp,
              proc = "ParallelGatekeepingAdj",
              par = parameters(family = family,
                               proc = families(family1 ="HochbergAdj", family2 = "HochbergAdj"),
                               gamma = gamma))

[1] 0.01733333 0.01733333 0.01733333 0.01733333
```

gMCP with Simes test:
```{r}
m <- rbind(H1=c(0, 0.5, 0.25, 0.25),
           H2=c(0.5, 0, 0.25, 0.25),
           H3=c(0, 0, 0, 1),
           H4=c(0, 0, 1, 0))
weights <- c(0.5, 0.5, 0, 0)
graph <- new("graphMCP", m=m, weights=weights)
pvalues <- c(0.01, 0.013, 0.01, 0.01)
gMCP(graph, pvalues, test="Simes", alpha=0.05)
```
![obraz](https://user-images.githubusercontent.com/60151643/219380680-e821b89c-6a8f-4a27-8fe5-6f506a61fbff.png)

I get from the CTP:

```{r}
Remaining hypotheses (new numbering):
1: H1
2: H2
3: H3
4: H4
Subset {4} (padj: 0.01): p_4=0.01<=a*(w_4)     =0.05*(1)=0.05
Subset {3} (padj: 0.01): p_3=0.01<=a*(w_3)     =0.05*(1)=0.05

Subset {3,4} (padj: 0.01): p_4=0.01<=a*(w_3+w_4)     =0.05*(0.5+0.5)=0.05

Subset {2} (padj: 0.0173333333333333): p_2=0.013<=a*(w_2)     =0.05*(0.75)=0.0375

Subset {2,4} (padj: 0.013): p_4=0.01<=a*(w_4)     =0.05*(0.25)=0.0125
Subset {2,3} (padj: 0.013): p_3=0.01<=a*(w_3)     =0.05*(0.25)=0.0125
Subset {2,3,4} (padj: 0.013): p_4=0.01<=a*(w_3+w_4)     =0.05*(0.125+0.125)=0.0125

Subset {1} (padj: 0.0133333333333333): p_1=0.01<=a*(w_1)     =0.05*(0.75)=0.0375

Subset {1,4} (padj: 0.01): p_4=0.01<=a*(w_1+w_4)     =0.05*(0.75+0.25)=0.05
Subset {1,3} (padj: 0.01): p_3=0.01<=a*(w_1+w_3)     =0.05*(0.75+0.25)=0.05
Subset {1,3,4} (padj: 0.01): p_4=0.01<=a*(w_1+w_3+w_4)     =0.05*(0.75+0.125+0.125)=0.05
Subset {1,2} (padj: 0.013): p_2=0.013<=a*(w_1+w_2)     =0.05*(0.5+0.5)=0.05
Subset {1,2,4} (padj: 0.013): p_4=0.01<=a*(w_1+w_4)     =0.05*(0.5+0)=0.025
Subset {1,2,3} (padj: 0.013): p_3=0.01<=a*(w_1+w_3)     =0.05*(0.5+0)=0.025
Subset {1,2,3,4} (padj: 0.013): p_4=0.01<=a*(w_1+w_3+w_4)     =0.05*(0.5+0+0)=0.025
```
Let's filter it:
![obraz](https://user-images.githubusercontent.com/60151643/219380956-237ee479-570c-408e-8c7d-f00cb8d55239.png)

For the same parameters and Holm (Bonferroni's approach) it agrees.

---
EDIT: Checked also with multxpert:
```{r}
F1 <- list(label = "F1", rawp=c(0.01, 0.013), proc = "Hochberg", procpar = 0.5)
F2 <- list(label = "F2", rawp=c(0.01, 0.01),  proc = "Hochberg", procpar = 1)

multxpert::pargateadjp(gateproc = list(F1, F2), independence = TRUE, printDecisionRules=TRUE)

Hypothesis testing problem

Global familywise error rate=0.05
Independence condition is imposed (the families are tested from first to last) 

Family 1 (F1) is tested using Hochberg procedure (truncation parameter=0.5) at alpha1=0.05.

Null hypothesis 1 (raw p-value=0.01) is rejected.
Null hypothesis 2 (raw p-value=0.013) is rejected.

Details on the decision rule for this family can be obtained by running the PValAdjP function for Hochberg procedure with gamma=0.5 and alpha=0.05.

One or more null hypotheses are rejected in Family 1 and the parallel gatekeeping procedure passes this family. Based on the error rate function of Hochberg procedure (truncation parameter=0.5), alpha2=0.05 is carried over to Family 2.

Family 2 (F2) is tested using Hochberg procedure (truncation parameter=1) at alpha2=0.05.

Null hypothesis 3 (raw p-value=0.01) is rejected.
Null hypothesis 4 (raw p-value=0.01) is rejected.

Details on the decision rule for this family can be obtained by running the PValAdjP function for Hochberg procedure with gamma=1 and alpha=0.05.

  Family Procedure Parameter Raw.pvalue Adj.pvalue
1     F1  Hochberg       0.5      0.010     0.0173
2     F1  Hochberg       0.5      0.013     0.0173
3     F2  Hochberg       1.0      0.010     0.0173
4     F2  Hochberg       1.0      0.010     0.0173
```

Literature:
- https://cran.r-project.org/web/packages/gMCP/vignettes/gMCP.pdf

PS: in any case, gMCP seems to use the formulas provided here:
- https://onlinelibrary.wiley.com/doi/full/10.1002/bimj.201000239
- http://www.meduniwien.ac.at/fwf_adaptive/papers/bretz_2009_22.pdf
- https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=179d7b170048360a00877b55f9b8073ae1143009
- https://arxiv.org/pdf/1812.00250.pdf

**Comment by gpaux** [comment]
Mediana and multxpert implement the method provided in the following paper
Alex Dmitrienko , George Kordzakhia & Ajit C. Tamhane (2011) Multistage and Mixture Parallel Gatekeeping Procedures in Clinical Trials, Journal of Biopharmaceutical Statistics, 21:4, 726-747, [DOI: 10.1080/10543406.2011.551333](https://www.tandfonline.com/doi/full/10.1080/10543406.2011.551333)

I have manually re-calculated the adjusted p-values from your example, they match with the ones calculated by Mediana and multxpert.

Please review the documentation for gMCP to understand the differences with the Mixture Parallel Gatekeeping Procedures and the gMCP method with Simes test.

**Comment by Generalized** [comment]
Thank you very, very much for your work and immediate response!

The good news is that both packages agree (I checked 30 cases) for the Bonferroni (assumption-less) approach (fallback, fixed sequence, parallel with Holm and Bonferroni). This validation was important for me, as I often need the graph-based testing for more complex scenarios, like retesting and various paths between hypotheses. I will do a further research on the Simes approach and possibly debug the code step by step, as it looks close to Hochberg or Hommel so there must be something trivial I missed: a little bit different approach (so I check the *consistency* between them now) or a bug in the code.

Thank you, wholeheartedly, again!
